---
- name: Teste local
  hosts: jenkins
  vars_files:
    - vars.yml
  tasks:
    - name: Criando a instância EC2
      ec2:
        instance_type: t2.micro
        key_name: jan20
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        image: ami-062f7200baf2fa504
        wait: yes
        group: launch-wizard-2
        region: us-east-1
        vpc_subnet_id: subnet-95cfdfc9
        assign_public_ip: yes
      register: ec2

    - name: Add nova instancia ao grupo
      template:
        src: templates/inventory.j2
        dest: inventory_new
      loop: "{{ ec2.instances }}"

    - name: Corrigindo permissoes da key
      file:
        path: key/jan20
        mode: 0600

    - name: Aguardando o SSH subir
      pause:
        minutes: 1

